{
    "timestamp": "2023-12-02_18-16-12",
    "groups": {
        "1": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_1\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_1\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "f7f6d7ca1b0ca8179a28e9aa549ac4a84e5381aa"
        },
        "2": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_2\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_2\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\Car-Racing-Challenge\\test_file.py\", line 25, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x64)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "778fec3875c0eb58932db649a6a98e8e01f988d6"
        },
        "3": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_3\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_3\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "b60b72ceac11321e0678ee5f0fc47499a6d4c6a4"
        },
        "10": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_10\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_10\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "f7f6d7ca1b0ca8179a28e9aa549ac4a84e5381aa"
        },
        "11": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_11\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_11\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\Car-Racing-Challenge\\test_file.py\", line 25, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x64)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "778fec3875c0eb58932db649a6a98e8e01f988d6"
        },
        "12": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_12\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_12\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "b60b72ceac11321e0678ee5f0fc47499a6d4c6a4"
        },
        "21": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_21\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_21\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "f7f6d7ca1b0ca8179a28e9aa549ac4a84e5381aa"
        },
        "22": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_22\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_22\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\Car-Racing-Challenge\\test_file.py\", line 25, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x64)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "778fec3875c0eb58932db649a6a98e8e01f988d6"
        },
        "23": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_23\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_23\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "b60b72ceac11321e0678ee5f0fc47499a6d4c6a4"
        },
        "31": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_31\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_31\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "f7f6d7ca1b0ca8179a28e9aa549ac4a84e5381aa"
        },
        "32": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_32\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_32\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\Car-Racing-Challenge\\test_file.py\", line 25, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x64)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "778fec3875c0eb58932db649a6a98e8e01f988d6"
        },
        "33": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_33\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_33\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "b60b72ceac11321e0678ee5f0fc47499a6d4c6a4"
        },
        "41": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_41\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_41\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "f7f6d7ca1b0ca8179a28e9aa549ac4a84e5381aa"
        },
        "42": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_42\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_42\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\Car-Racing-Challenge\\test_file.py\", line 25, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x64)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "778fec3875c0eb58932db649a6a98e8e01f988d6"
        },
        "43": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_43\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_43\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "b60b72ceac11321e0678ee5f0fc47499a6d4c6a4"
        },
        "51": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_51\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_51\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "f7f6d7ca1b0ca8179a28e9aa549ac4a84e5381aa"
        },
        "52": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_52\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_52\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\Car-Racing-Challenge\\test_file.py\", line 25, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x64)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "778fec3875c0eb58932db649a6a98e8e01f988d6"
        },
        "53": {
            "error": true,
            "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_53\\evaluation_script.py\", line 79, in <module>\n    mean_reward, std_reward = evaluate_agent(model_file, agent_interface, seed=args.seed, tracks=tracks)\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car_Racing_Challenge\\students_repo\\group_53\\evaluation_script.py\", line 47, in evaluate_agent\n    output = model(state)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"C:\\Users\\limar\\miniconda3\\envs\\car-racing-evaluation\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\nRuntimeError: The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__.py\", line 10, in forward\n    x: Tensor) -> Tensor:\n    dummy_network = self.dummy_network\n    return (dummy_network).forward(x, )\n            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"code/__torch__/torch/nn/modules/container.py\", line 18, in forward\n    _3 = getattr(self, \"3\")\n    _4 = getattr(self, \"4\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    input2 = (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/linear.py\", line 14, in forward\n    weight = self.weight\n    bias = self.bias\n    return torch.linear(input, weight, bias)\n           ~~~~~~~~~~~~ <--- HERE\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"C:\\Users\\limar\\Desktop\\Studium\\Hiwi\\Car-Racing-Challenge\\test_file.py\", line 20, in forward\n    def forward(self, x):\n        return self.dummy_network(x)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 139, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"C:\\Users\\limar\\miniconda3\\envs\\uncertainty-rl\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return F.linear(input, self.weight, self.bias)\n               ~~~~~~~~ <--- HERE\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (1x416 and 4x16)\n\n]",
            "mean": -1,
            "std": -1,
            "commit-SHA": "b60b72ceac11321e0678ee5f0fc47499a6d4c6a4"
        }
    }
}